spring.application.name=findora

# Server Port
server.port=8080

# Database Configuration (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/findora_db
spring.datasource.username=root
spring.datasource.password=pragun17
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Optional: show SQL parameter values (useful for debugging)
logging.level.org.hibernate.orm.jdbc.bind=TRACE